on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: DK Test Hello World
        id: foo
        uses: crmlogician/hello-world-composite-action@v12
        with:
          who-to-greet: 'Mona the Octocat'
        secrets: 
          token: ready
      - uses: actions/checkout@v3
      - run: |
          echo using v6
          echo random-number ${{ steps.foo.outputs.random-number }}
          echo secret SFDC_CLIENT_ID ${{ secrets.SFDC_CLIENT_ID }}
          echo secret SFDC_CLIENT_SECRET ${{ secrets.SFDC_CLIENT_SECRET }}
        shell: bash