on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: DK Test Hello World
        id: foo
        uses: crmlogician/hello-world-composite-action@v2

        with:
          who-to-greet: 'Mona the Octocat'
      - uses: actions/checkout@v3
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
